language: go

go:
  - 1.11.x
  - 1.x

env:
  - GO111MODULE=on

git:
  depth: 1

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libx11-dev libxi-dev

install: true

script:
  - go build ./...
  - go vet ./...
  - gofmt -l -e -d .
